AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - "node_modules/**/*"
    - "bower_components/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - Gemfile
    - Guardfile
    - Rakefile

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/LineLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"
    - "app/controllers/**"
    - "test/controllers/**"


Metrics/MethodLength:
  Max: 12
  Exclude:
    - "db/migrate/*"
    - "test/**/*"

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**"

Rails/RefuteMethods:
  Enabled: false

Rails/Validation:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: true

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "app/controllers/**"
    - "test/controller/**"
    - "test/models/**"

Style/TrivialAccessors:
  AllowPredicates: true
